version: "3.8"

services:
  redis-service:
    image: redis:alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - app-network

  visit-service:
    build: ./visit-service
    container_name: visit-service
    ports:
      - "4001:4001"
    depends_on:
      - redis-service
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379

  logger-service:
    build: ./logger-service
    container_name: logger-service
    ports:
      - "4002:4002"
    depends_on:
      - visit-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
